spring.application.name=GestionalePensione
# PostgreSQL Config
spring.datasource.url=jdbc:postgresql://localhost:5432/pensione_canina
spring.datasource.username=postgres
spring.datasource.password=waterpolo11
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

